#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/6/12 1:22 下午
# @Author  : yxChen

LOG_ROUTE = 'LOG.ROUTE.'

API_LOGIN = LOG_ROUTE + 'LOGIN'
API_PROJECT = LOG_ROUTE + 'PROJECT'
API_REQUEST = LOG_ROUTE + 'PROJECT.REQUEST'
API_REPORT = LOG_ROUTE + 'PROJECT.REPORT'
API_OVERVIEW = LOG_ROUTE + 'PROJECT.OVERVIEW'
API_EDITOR = LOG_ROUTE + 'PROJECT.EDITOR'
EXECUTE_SUITE = 'PROJECT.EXECUTE_SUITE'
API_PROJECT_CASE = LOG_ROUTE + 'PROJECT.CASE'
API_WORKSTATION = LOG_ROUTE + 'WORKSTATION'
